FORMAT: 1A
HOST: https://api.test.paysafe.com/

# Paysafe Batch Applications

Partners can batch their queries with Merchant Reference Number. Further, Paysafe would supply Batch ID for the given Mechant Reference Number.

1. A batch request is a single API call that uploads a large number of onboarding app queries at once. 
2. Merchants can use the merchant reference number to batch their requests. Paysafe would also provide a Batch ID for the specified Merchant Reference Number if the batch was successfully submitted.
3. Once the batch has been approved, individual applications will be processed.

## Advantages
Using the Batch Applications, user can submit multiple merchant applications within a single request. This will reduce the painful process of creating and referring multiple applications.
Request for multiple Merchant Legal Entity (MLE) will be part of 1 batch request
Request for multiple Locations for each MLE will be part of 1 batch request
Request to configure multiple bank accounts for each MLE will be part of 1 batch request
End to end automated underwriting is supported
Automated account provisioning for the approved applications is supported
API responses and webhooks are triggered for errors occurred during application processing

## Request Attributes

The following tables include the mandatory and optional parameters for create Batch Application request. For a detailed description of the attributes listed in these tables, please refer to the Application Batch Object

## Prerequisites

Field validations template has to be selected by the OPS team while creating the config

## Constraints

# Release Notes

| Version   | Date                 | Details |
|---        |---                   |---      |
| v1        |6th Jan 2022          | Initial Draft|

# Overview

Connect your application directly with our payment engine to process a full suite of methods that are REST-based – designed to be easy to understand and use. Ultimate control puts you in the driver’s seat.
* Choose an efficient, lightweight, and fast integration method to access our API.
* Implement a wide variety of REST-based API requests – including Purchases, Refunds, and Void  Authorizations.
* Obtain output in JSON format – it’s easy to parse in a large variety of Web and mobile applications.
* Use any language or platform to make requests through standard HTTP protocols.

<a name="apikey" title="Authentication"></a>
# Authentication

In order for you to use the Paysafe REST API, Paysafe must first set you up on their system
and provide you with an API key. Your API key looks something like this:

 * Key Username – MerchantXYZ
 * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

Note that this is not the same as your Merchant Back Office username and password.

The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:

 1. The Key Username and Key Password are combined into a string separated by a colon, e.g.,“Key Username:Key Password”.
 2. The resulting string literal is then encoded using Base64.
 3. The authorization method and a space (i.e., “Basic”) are then put before the encoded string.

For example, using the Key Username and Password examples above, the header is formed as follows:

``Authorization: Basic
TWVyY2hhbnRYWVo6Qi10c3QxLTAtNTFlZDM5ZTQtMzEyZDAyMzQ1ZDNmMTIzMTIwODgxZGZmOWJiNDAyMGE4OWU4YWM0NGNkZmRjZWNkNzAyMTUxMTgyZmRjOTU yMjcyNjYxZDI5MGFiMmU1ODQ5ZTMxYmIwM2RlZWRlN2U=``

For additional details, please refer to [http://en.wikipedia.org/wiki/Basic_access_authentication](http://en.wikipedia.org/wiki/Basic_access_authentication).

**Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that it is used appropriately for your needs.

# URLs

##  Test URL
In order to test your integration with Paysafe, use the following Test URL:

`https://api.test.paysafe.com`

For example:

`https://api.test.paysafe.com/v1/applicationbatches/<batchId>}`

## Production URL
In order to process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com`

For example:

`https://api.paysafe.com/v1/applicationbatches/<batchId>}`

## Application Batch Objects

|Element               |Json Key                  |Types                                                    |Constraints   |Mandatory            |Description                                                          |
|---                   |---                       |---                                                      |---           |---                  |---                                                                  |                                                    
| merchantRefNum       |merchantRefNum            | String                                                  |NA            |True                 |Reference Number from merchant for complete batch                    |
| applications       |applications                | Array of Consolidated Application Object                |NA            |True                 |Array of Applications                                                |

# Error Codes

|Http Code|Error Code     |Description|
|---      |---            |---        |
|400      |5068           |Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected.         |

# Mandatory Fields

|Field|Type|Description|Valid Example Data|
|---                   |---                       |---   |---   |
|application.onboardingConfigId|string|Onboarding Config Id cannot be blank. This id is provided by Paysafe Onboarding team.|140144|
|application.bankaccount|string|Bank account cannot be empty||
|application.merchantRefNum|string|Merchant ref number cannot be blank|123123132|
|application.acceptTermsAndConditions|boolean|AssertTrue, terms and conditions should be accepted for submitting the application|TRUE|
|application.businessLegalEntity|string|Business legal entity cannot be null||
|application.users|string|Atleast one user is mandatory for requesting an application||
|application.acceptTermsAndConditions|boolean|Terms and conditions cannot be null|TRUE|
|user.email|string|User email cannot be blank|user@compay.com|
|user.loginName|string|User login name cannot be blank|Micheal|
|user.password|string|Password cannot be blank|P@ssw04d|
|businessLegalEntity.address|string|Address cannot be null||
|businessLegalEntity.id|string|id cannot be null|Required for ADD_LOCATION, ADD_ACCOUNT|
|businessLegalEntity.taxIdentificationNumber|string|\\d{9}, 9 digit number|123456789|
|businessLegalEntity.taxIdentificationNumber|string|tax Identification Number cannot be blank|123456789|
|businessLegalEntity.principals|string|Principals cannot be empty|
|businessLegalEntity.legalName|string|Legal Name cannot be blank paysafe company|
|businessLegalEntity.type|string|Type cannot be null|CHARITY, CIC, CLUB, CORP, GOV, INDIVIDUAL, LLC, LLP, LTD, NPCORP, OTHER, PARTNERSHP, PLC, SOLEPROP, TRUST|
|businessLegalEntity.businessDetails|string|Business Details cannot be empty||
|businessDetails.accounts|string|Accounts cannot be empty||
|businessDetails.tradeName|string|Trade Name cannot be blank|paysafe trading co.|
|businessDetails.id|string|id dannot be null|required for ADD_ACCOUNT|
|businessDetails.category|string|Category cannot be null EDU||
|statementDescriptor.phone|string|Phone cannot be empty|8932223111|
|statementDescriptor.descriptor|string|01 to 20, descriptor should be of length 1-20 characters some card description||
|address.state|string|state cannot be empty|TX|
|address.country|string|country cannot be empty|US|
|address.city|string|city cannot be empty|Houston|
|address.zip|string|zip cannot be empty|77001|
|address.street|string|street cannot be empty|St. peter's Church street|
|contact.firstName|string|First name cannot be empty|Micheal|
|account.settlementCurrency|string|Settlement currency cannot be null|USD|
|account.paymentType|string|payment Type cannot be null|CC, DD|
|account.currency|string|currency cannot be null|USD|
|account.statementDescriptor|string|statement Descriptor cannot be null||
|principal.lastName|string|Last Name cannot be blank|Waugh|
|principal.address|string|Address cannot be null|Old Church Street|
|principal.firstName|string|First Name cannot be blank|Micheal|
|principal.positionInCompany|string|Position In Company cannot be blank|Trustee|
|principal.dateOfBirth|string|date Of Birth cannot be null||
|statementDescriptor.phone|string|01 to 13, phone should between 1 - 13 digits length|+1 832-395-1500|
|statementDescriptor.descriptor|string|Descriptor cannot be empty|card description||
|achBankAccount.routingNumber|string|routing Number cannot be blank|524871232|
|achBankAccount.accountNumber|string|account Number cannot be blank|2082649738|

# Error Examples

## Error Example - 1:  Submitted a request that is missing a mandatory field


```apib

RESPONSE

    {
    "error": {
        "code": "5068",
        "message": "Field error(s)",
        "details": [
            "Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected."
        ],
        "fieldErrors": [
            {
                "field": "applications",
                "error": "must not be empty"
            }
        ]
    }
}
```
## Error Example - 2:  Submitted a request that is missing a mandatory field


```apib

RESPONSE

{
    "error": {
        "code": "5068",
        "message": "Field error(s)",
        "details": [
            "Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected."
        ],
        "fieldErrors": [
            {
                "field": "merchantRefNum",
                "error": "must not be blank"
            },
            {
                "field": "applications",
                "error": "must not be empty"
            }
        ]
    }
}
```


## Submit Batch [/merchant/v1/applicationbatches]

### Submit Batch [POST /merchant/v1/applicationbatches]

+ Parameters
    + merchantRefNumber: `976559030` (string, required) - This is the unique reference number of the payment; merchant can identify the transaction by submitting this merchantRefNumber.
    + applications: `name": "name", "onboardingConfigId": "221444","locale": "en_us",` (string, required) - Applications specify a set of steps and their execution order.

+ Attributes 
    + Include SubmitBatchObject

+ Request (application/json)

    {
      "merchantRefNum": "12311112",
      "applications": [
        {
          "name": "name",
          "merchantRefNum": "1231111",
          "onboardingConfigId": "221444",
          "locale": "en_us",
          "metaData": null,
          "submit": true,
          "statusReason": null,
          "businessLegalEntity": {
            "type": "LTD",
            "legalName": "{{legal_name}}",
            "registrationNumber": "F01011",
            "taxIdentificationNumber": "TAX123456",
            "description": "Diesel motors and vehicles",
            "users": [
          {
            "email": "{{bleemail}}",
            "fullName": "{{bleusername}}",
            "loginName": "{{bleusername}}",
            "password": "Pwd1234!"
          }
        ],
        "achBankAccount": null,
        "bacsBankAccount": null,
        "sepaBankAccount": null,
        "wireBankAccount": null,
        "eftBankAccount": null,
        "address": {
          "street": "2600 Michelson Drive",
          "street2": "Suite 1600",
          "city": "Irvine",
          "state": "CA",
          "country": "ES",
          "zip": "92612"
        },
        "businessDetails": [
          {
            "tradeName": "Good Office Services USA",
            "tradeAddress": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "Irvine",
              "state": "CA",
              "country": "ES",
              "zip": "92612"
            },
            "category": "ACCT",
            "mcc": null,
            "website": "https://goodoffice.us",
            "phoneNumber": {
              "countryCode": "+1",
              "number": "9090909090"
            },
            "email": "support@goodoffice.us",
            "users": [
              {
                "email": "{{bdemail}}",
                "fullName": "{{bdusername}}",
                "loginName": "{{bdusername}}",
                "password": "Pwd1234!",
                "status": null
              }
            ],
            "achBankAccount": null,
            "bacsBankAccount": null,
            "sepaBankAccount": null,
            "wireBankAccount": null,
            "eftBankAccount": null,
            "accounts": [
              {
                "name": "CARD USD Account",
                "type": "MERCHANT",
                "paymentType": "CARD",
                "currency": "GBP",
                "settlementCurrency": "GBP",
                "statementDescriptor": {
                  "descriptor": "Good Office Services",
                  "phone": "9090909090"
                },
                "terminalType": "ECOM",
                "cardTypes": [
                  "VI",
                  "MC"
                ],
                "processingOptions": [
                  {
                    "cardType": "AM",
                    "mid": "454545",
                    "tids": [
                      "2221",
                      "333233"
                    ]
                  }
                ],
                "users": [
                  {
                    "email": "{{acctemail}}",
                    "fullName": "{{acctusername}}",
                    "loginName": "{{acctusername}}",
                    "password": "Pwd1234!"
                  }
                ],
                "achBankAccount": null,
                "bacsBankAccount": {
                  "accountNumber": "94001521",
                  "beneficiaryAccountName": "Main",
                  "beneficiaryBankCountry": "GB",
                  "sortCode": "857412"
                },
                "sepaBankAccount": null,
                "wireBankAccount": null,
                "eftBankAccount": null
              }
            ],
            "contacts": [
              {
                "type": "SALES",
                "title": "Mr",
                "firstName": "Good",
                "lastName": "Human",
                "middleName": "Ok",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.us"
              }
            ]
          }
        ],
        "principals": [
          {
            "title": "Mr",
            "firstName": "Susumumu",
            "lastName": "Hosoinon",
            "middleName": null,
            "previousLastName": null,
            "dateOfBirth": {
              "day": "28",
              "month": "02",
              "year": "1984"
            },
            "ssn": "123456789",
            "sin": null,
            "positionInCompany": "Chairman",
            "percentageShareholding": 40,
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "Irvine",
              "state": "CA",
              "country": "US",
              "zip": "92612"
            },
            "ubo": false,
            "applicant": false
          }
        ]
      }
    },
    {
      "name": null,
      "merchantRefNum": "123243",
      "onboardingConfigId": "221444",
      "locale": "en_us",
      "metaData": null,
      "submit": true,
      "statusReason": null,
      "businessLegalEntity": {
        "type": "LTD",
        "legalName": "{{legal_name1}}",
        "registrationNumber": "F01011",
        "taxIdentificationNumber": "TAX123456",
        "description": "Diesel motors and vehicles",
        "users": [
          {
            "email": "{{bleemail1}}",
            "fullName": "{{bleusername1}}",
            "loginName": "{{bleusername1}}",
            "password": "Pwd1234!"
          }
        ],
        "achBankAccount": null,
        "bacsBankAccount": null,
        "sepaBankAccount": null,
        "wireBankAccount": null,
        "eftBankAccount": null,
        "address": {
          "street": "2600 Michelson Drive",
          "street2": "Suite 1600",
          "city": "Irvine",
          "state": "CA",
          "country": "ES",
          "zip": "92612"
        },
        "businessDetails": [
          {
            "tradeName": "Good Office Services USA",
            "tradeAddress": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "Irvine",
              "state": "CA",
              "country": "ES",
              "zip": "92612"
            },
            "category": "ACCT",
            "mcc": null,
            "website": "https://goodoffice.us",
            "phoneNumber": {
              "countryCode": "+1",
              "number": "9090909090"
            },
            "email": "support@goodoffice.us",
            "users": [
              {
                "email": "{{bdemail1}}",
                "fullName": "{{bdusername1}}",
                "loginName": "{{bdusername1}}",
                "password": "Pwd1234!",
                "status": null
              }
            ],
            "achBankAccount": null,
            "bacsBankAccount": null,
            "sepaBankAccount": null,
            "wireBankAccount": null,
            "eftBankAccount": null,
            "accounts": [
              {
                "name": "CARD USD Account",
                "type": "MERCHANT",
                "paymentType": "CARD",
                "currency": "GBP",
                "settlementCurrency": "GBP",
                "statementDescriptor": {
                  "descriptor": "Good Office Services",
                  "phone": "9090909090"
                },
                "terminalType": "ECOM",
                "cardTypes": [
                  "VI",
                  "MC"
                ],
                "processingOptions": [
                  {
                    "cardType": "AM",
                    "mid": "454545",
                    "tids": [
                      "2221",
                      "333233"
                    ]
                  }
                ],
                "users": [
                  {
                    "email": "{{acctemail1}}",
                    "fullName": "{{acctusername1}}",
                    "loginName": "{{acctusername1}}",
                    "password": "Pwd1234!"
                  }
                ],
                "achBankAccount": null,
                "bacsBankAccount": {
                  "accountNumber": "94001521",
                  "beneficiaryAccountName": "Main",
                  "beneficiaryBankCountry": "GB",
                  "sortCode": "857412"
                },
                "sepaBankAccount": null,
                "wireBankAccount": null,
                "eftBankAccount": null
              }
            ],
            "contacts": [
              {
                "type": "SALES",
                "title": "Mr",
                "firstName": "Good",
                "lastName": "Human",
                "middleName": "Ok",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.us"
              }
            ]
          }
        ],
        "principals": [
          {
            "title": "Mr",
            "firstName": "Susumumu",
            "lastName": "Hosoinon",
            "middleName": null,
            "previousLastName": null,
            "dateOfBirth": {
              "day": "28",
              "month": "02",
              "year": "1984"
            },
            "ssn": "123456789",
            "sin": null,
            "positionInCompany": "Chairman",
            "percentageShareholding": 40,
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "Irvine",
              "state": "CA",
              "country": "US",
              "zip": "92612"
            },
            "ubo": false,
            "applicant": false
          }
        ]
      }
    }
  ]
}

+ Response 201 (application/json)

    + Body

        {
          "merchantRefNum": "12311112",
           "batchId": "81c67e4f-0358-4360-8fcc-f2fcd47f9e3b",
        }


## Get Application Batch by Id [/merchant/v1/applicationbatches/<batchId>]

### Get Application Batch by Id [GET /merchant/v1/applicationbatches/ec8e0615-9057-4075-9abb-14a3c65530d6]

+ Parameters
    + batch_id: `ec8e0615-9057-4075-9abb-14a3c65530d6` (string, required) - This is the unique reference number of the payment; merchant can identify the transaction by submitting this batchid.
    
+ Request (application/json)

Do not supply a request body for GET method.            

+ Response 201 (application/json) - Get Application Batch without Errors

        {
          "batchId": "a120530f-6684-4066-9740-4dc1023c07f8",
          "merchantRefNum": "604207874",
          "applications": [
            {
          "id": "248247365",
          "type": "INITIAL_APPLICATION",
          "merchantRefNum": "1604207874",
          "onboardingConfigId": "109774",
          "locale": "en",
          "acceptTermsAndConditions": true,
          "submit": true,
          "batchId": "a120530f-6684-4066-9740-4dc1023c07f8",
          "status": "APPROVED",
          "statusReasonCode": "AUTO_DECISION",
          "businessLegalEntity": {
            "id": "30a6da39-12f0-49d1-a6df-03df9a229b83",
            "type": "LLC",
            "legalName": "Good Guy INC US",
            "taxIdentificationNumber": "987654321",
            "description": "abc",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            },
        "businessDetails": [
          {
            "id": "f0a15493-6833-48fb-867e-4155df401f54",
            "tradeName": "Good Office Services US",
            "tradeAddress": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            },
            "category": "ACCT",
            "website": "https://www.merchantofpaysafeus.com",
            "phoneNumber": {
              "countryCode": "+1",
              "number": "9090909091"
            },
            "email": "supportgoodofficeus@gmail.com",
            "accounts": [
              {
                "id": "1004967140",
                "name": "CARD USD Account1",
                "paymentType": "CARD",
                "currency": "USD",
                "settlementCurrency": "USD",
                "statementDescriptor": {
                  "descriptor": "descriptor",
                  "phone": "8932223111"
                },
                "terminalType": "ECOM",
                "users": [
                  {
                    "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741a",
                    "loginName": "bleusername6042078741a"
                  },
                  {
                    "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741b",
                    "loginName": "bleusername6042078741b"
                  },
                  {
                    "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741c",
                    "loginName": "bleusername6042078741c"
                  },
                  {
                    "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741d",
                    "loginName": "bleusername6042078741d"
                  },
                  {
                    "id": "90270633-0a37-4ba2-9937-e23649756988",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741e",
                    "loginName": "bleusername6042078741e"
                  }
                ],
                "achBankAccount": {
                  "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                  "lastDigits": "38",
                  "routingNumber": "524871232"
                }
              },
              {
                "id": "1004967290",
                "name": "CARD USD Account1",
                "paymentType": "CARD",
                "currency": "USD",
                "settlementCurrency": "USD",
                "statementDescriptor": {
                  "descriptor": "descriptor",
                  "phone": "8932223111"
                },
                "terminalType": "ECOM",
                "users": [
                  {
                    "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741a",
                    "loginName": "bleusername6042078741a"
                  },
                  {
                    "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741b",
                    "loginName": "bleusername6042078741b"
                  },
                  {
                    "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741c",
                    "loginName": "bleusername6042078741c"
                  },
                  {
                    "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741d",
                    "loginName": "bleusername6042078741d"
                  },
                  {
                    "id": "90270633-0a37-4ba2-9937-e23649756988",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741e",
                    "loginName": "bleusername6042078741e"
                  }
                ],
                "achBankAccount": {
                  "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                  "lastDigits": "38",
                  "routingNumber": "524871232"
                }
              },
              {
                "id": "1004967430",
                "name": "CARD USD Account1",
                "paymentType": "CARD",
                "currency": "USD",
                "settlementCurrency": "USD",
                "statementDescriptor": {
                  "descriptor": "descriptor",
                  "phone": "8932223111"
                },
                "terminalType": "ECOM",
                "users": [
                  {
                    "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741a",
                    "loginName": "bleusername6042078741a"
                  },
                  {
                    "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741b",
                    "loginName": "bleusername6042078741b"
                  },
                  {
                    "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741c",
                    "loginName": "bleusername6042078741c"
                  },
                  {
                    "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741d",
                    "loginName": "bleusername6042078741d"
                  },
                  {
                    "id": "90270633-0a37-4ba2-9937-e23649756988",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741e",
                    "loginName": "bleusername6042078741e"
                  }
                ],
                "achBankAccount": {
                  "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                  "lastDigits": "38",
                  "routingNumber": "524871232"
                }
              },
              {
                "id": "1004967540",
                "name": "CARD USD Account1",
                "paymentType": "CARD",
                "currency": "USD",
                "settlementCurrency": "USD",
                "statementDescriptor": {
                  "descriptor": "descriptor",
                  "phone": "8932223111"
                },
                "terminalType": "ECOM",
                "users": [
                  {
                    "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741a",
                    "loginName": "bleusername6042078741a"
                  },
                  {
                    "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741b",
                    "loginName": "bleusername6042078741b"
                  },
                  {
                    "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741c",
                    "loginName": "bleusername6042078741c"
                  },
                  {
                    "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741d",
                    "loginName": "bleusername6042078741d"
                  },
                  {
                    "id": "90270633-0a37-4ba2-9937-e23649756988",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741e",
                    "loginName": "bleusername6042078741e"
                  }
                ],
                "achBankAccount": {
                  "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                  "lastDigits": "38",
                  "routingNumber": "524871232"
                }
              },
              {
                "id": "1004967640",
                "name": "CARD USD Account1",
                "paymentType": "CARD",
                "currency": "USD",
                "settlementCurrency": "USD",
                "statementDescriptor": {
                  "descriptor": "descriptor",
                  "phone": "8932223111"
                },
                "terminalType": "ECOM",
                "users": [
                  {
                    "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741a",
                    "loginName": "bleusername6042078741a"
                  },
                  {
                    "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741b",
                    "loginName": "bleusername6042078741b"
                  },
                  {
                    "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741c",
                    "loginName": "bleusername6042078741c"
                  },
                  {
                    "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741d",
                    "loginName": "bleusername6042078741d"
                  },
                  {
                    "id": "90270633-0a37-4ba2-9937-e23649756988",
                    "email": "bleemail604207874@gmail.com",
                    "fullName": "bleusername6042078741e",
                    "loginName": "bleusername6042078741e"
                  }
                ],
                "achBankAccount": {
                  "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                  "lastDigits": "38",
                  "routingNumber": "524871232"
                }
              }
            ],
            "contacts": [
              {
                "id": "ab4fa869-77f6-4cea-9149-07a584167fb3",
                "firstName": "Good",
                "lastName": "Human1",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.com"
              },
              {
                "id": "7ef99ef7-867b-48c6-a85d-54b9a55e400f",
                "firstName": "Good",
                "lastName": "Human1",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.com"
              },
              {
                "id": "5da5bb43-3f6b-482c-8f75-d35754e4a4f4",
                "firstName": "Good",
                "lastName": "Human1",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.com"
              },
              {
                "id": "94ade9f0-88a7-49d6-aec1-ffc1fd88545c",
                "firstName": "Good",
                "lastName": "Human1",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.com"
              },
              {
                "id": "7c4cc663-358c-46b9-b3a1-85108ae31dac",
                "firstName": "Good",
                "lastName": "Human1",
                "phoneNumber": {
                  "countryCode": "+1",
                  "number": "9090909090"
                },
                "email": "goodhuman@goodoffice.com"
              }
            ]
          }
        ],
        "principals": [
          {
            "id": "69d9b928-58e2-4a72-97f1-ffd5ff8d23d9",
            "isApplicant": true,
            "isControlProng": true,
            "firstName": "Sophie",
            "lastName": "Hosoinon1",
            "dateOfBirth": {
              "day": 28,
              "month": 2,
              "year": 1984
            },
            "ssnLastFour": "2234",
            "positionInCompany": "Chairman",
            "type": "OWNER",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            }
          },
          {
            "id": "2f0b72a9-6a89-4ce3-a218-efd83bda269b",
            "isApplicant": false,
            "isControlProng": false,
            "firstName": "Sophie",
            "lastName": "Hosoinon2",
            "dateOfBirth": {
              "day": 28,
              "month": 2,
              "year": 1984
            },
            "ssnLastFour": "2234",
            "positionInCompany": "Chairman",
            "type": "OWNER",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            }
          },
          {
            "id": "2d51d504-c34b-4972-8c6d-14af5169ef64",
            "isApplicant": false,
            "isControlProng": false,
            "firstName": "Sophie",
            "lastName": "Hosoinon3",
            "dateOfBirth": {
              "day": 28,
              "month": 2,
              "year": 1984
            },
            "ssnLastFour": "2234",
            "positionInCompany": "Chairman",
            "type": "OWNER",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            }
          },
          {
            "id": "ba76cd7a-d810-4615-8c1e-71fb3b3ec488",
            "isApplicant": false,
            "isControlProng": false,
            "firstName": "Sophie",
            "lastName": "Hosoinon4",
            "dateOfBirth": {
              "day": 28,
              "month": 2,
              "year": 1984
            },
            "ssnLastFour": "2234",
            "positionInCompany": "Chairman",
            "type": "OWNER",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            }
          },
          {
            "id": "a51e39a3-f41d-4784-9104-681bc86e6eba",
            "isApplicant": false,
            "isControlProng": false,
            "firstName": "Sophie",
            "lastName": "Hosoinon5",
            "dateOfBirth": {
              "day": 28,
              "month": 2,
              "year": 1984
            },
            "ssnLastFour": "2234",
            "positionInCompany": "Chairman",
            "type": "OWNER",
            "address": {
              "street": "2600 Michelson Drive",
              "street2": "Suite 1600",
              "city": "California",
              "state": "CA",
              "country": "US",
              "zip": "90201"
            }
          }
        ]
      },
      "termsVersion": [
        {
          "region": "US",
          "termsAndConditions": "10.1"
        }
      ]
    }
  ]
}


## Get Application Batch by Merchant Reference Number  [/merchant/v1/applicationbatches?merchantRefNum=<merchantRefNumber>]

### Get Application Batch by Merchant Reference Number [GET /merchant/v1/applicationbatches?merchantRefNum=976559030]

+ Parameters
    + merchantRefNumber: `976559030` (string, required) - This is the unique reference number of the payment; merchant can identify the transaction by submitting this merchantRefNumber.
    
+ Request (application/json)

Do not supply a request body for GET method.            

+ Response 201 (application/json) - Get Application Batch by Merchant Reference Number without Errors

    + Body
    

            {
              "batchId": "a120530f-6684-4066-9740-4dc1023c07f8",
              "merchantRefNum": "604207874",
              "applications": [
                {
                  "id": "248247365",
                  "type": "INITIAL_APPLICATION",
                  "merchantRefNum": "1604207874",
                  "onboardingConfigId": "109774",
                  "locale": "en",
                  "acceptTermsAndConditions": true,
                  "submit": true,
                  "batchId": "a120530f-6684-4066-9740-4dc1023c07f8",
                  "status": "APPROVED",
                  "statusReasonCode": "AUTO_DECISION",
                  "businessLegalEntity": {
                    "id": "30a6da39-12f0-49d1-a6df-03df9a229b83",
                    "type": "LLC",
                    "legalName": "Good Guy INC US",
                    "taxIdentificationNumber": "987654321",
                    "description": "abc",
                    "address": {
                      "street": "2600 Michelson Drive",
                      "street2": "Suite 1600",
                      "city": "California",
                      "state": "CA",
                      "country": "US",
                      "zip": "90201"
                    },
                    "businessDetails": [
                      {
                        "id": "f0a15493-6833-48fb-867e-4155df401f54",
                        "tradeName": "Good Office Services US",
                        "tradeAddress": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        },
                        "category": "ACCT",
                        "website": "https://www.merchantofpaysafeus.com",
                        "phoneNumber": {
                          "countryCode": "+1",
                          "number": "9090909091"
                        },
                        "email": "supportgoodofficeus@gmail.com",
                        "accounts": [
                          {
                            "id": "1004967140",
                            "name": "CARD USD Account1",
                            "paymentType": "CARD",
                            "currency": "USD",
                            "settlementCurrency": "USD",
                            "statementDescriptor": {
                              "descriptor": "descriptor",
                              "phone": "8932223111"
                            },
                            "terminalType": "ECOM",
                            "users": [
                              {
                                "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741a",
                                "loginName": "bleusername6042078741a"
                              },
                              {
                                "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741b",
                                "loginName": "bleusername6042078741b"
                              },
                              {
                                "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741c",
                                "loginName": "bleusername6042078741c"
                              },
                              {
                                "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741d",
                                "loginName": "bleusername6042078741d"
                              },
                              {
                                "id": "90270633-0a37-4ba2-9937-e23649756988",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741e",
                                "loginName": "bleusername6042078741e"
                              }
                            ],
                            "achBankAccount": {
                              "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                              "lastDigits": "38",
                              "routingNumber": "524871232"
                            }
                          },
                          {
                            "id": "1004967290",
                            "name": "CARD USD Account1",
                            "paymentType": "CARD",
                            "currency": "USD",
                            "settlementCurrency": "USD",
                            "statementDescriptor": {
                              "descriptor": "descriptor",
                              "phone": "8932223111"
                            },
                            "terminalType": "ECOM",
                            "users": [
                              {
                                "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741a",
                                "loginName": "bleusername6042078741a"
                              },
                              {
                                "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741b",
                                "loginName": "bleusername6042078741b"
                              },
                              {
                                "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741c",
                                "loginName": "bleusername6042078741c"
                              },
                              {
                                "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741d",
                                "loginName": "bleusername6042078741d"
                              },
                              {
                                "id": "90270633-0a37-4ba2-9937-e23649756988",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741e",
                                "loginName": "bleusername6042078741e"
                              }
                            ],
                            "achBankAccount": {
                              "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                              "lastDigits": "38",
                              "routingNumber": "524871232"
                            }
                          },
                          {
                            "id": "1004967430",
                            "name": "CARD USD Account1",
                            "paymentType": "CARD",
                            "currency": "USD",
                            "settlementCurrency": "USD",
                            "statementDescriptor": {
                              "descriptor": "descriptor",
                              "phone": "8932223111"
                            },
                            "terminalType": "ECOM",
                            "users": [
                              {
                                "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741a",
                                "loginName": "bleusername6042078741a"
                              },
                              {
                                "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741b",
                                "loginName": "bleusername6042078741b"
                              },
                              {
                                "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741c",
                                "loginName": "bleusername6042078741c"
                              },
                              {
                                "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741d",
                                "loginName": "bleusername6042078741d"
                              },
                              {
                                "id": "90270633-0a37-4ba2-9937-e23649756988",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741e",
                                "loginName": "bleusername6042078741e"
                              }
                            ],
                            "achBankAccount": {
                              "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                              "lastDigits": "38",
                              "routingNumber": "524871232"
                            }
                          },
                          {
                            "id": "1004967540",
                            "name": "CARD USD Account1",
                            "paymentType": "CARD",
                            "currency": "USD",
                            "settlementCurrency": "USD",
                            "statementDescriptor": {
                              "descriptor": "descriptor",
                              "phone": "8932223111"
                            },
                            "terminalType": "ECOM",
                            "users": [
                              {
                                "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741a",
                                "loginName": "bleusername6042078741a"
                              },
                              {
                                "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741b",
                                "loginName": "bleusername6042078741b"
                              },
                              {
                                "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741c",
                                "loginName": "bleusername6042078741c"
                              },
                              {
                                "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741d",
                                "loginName": "bleusername6042078741d"
                              },
                              {
                                "id": "90270633-0a37-4ba2-9937-e23649756988",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741e",
                                "loginName": "bleusername6042078741e"
                              }
                            ],
                            "achBankAccount": {
                              "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                              "lastDigits": "38",
                              "routingNumber": "524871232"
                            }
                          },
                          {
                            "id": "1004967640",
                            "name": "CARD USD Account1",
                            "paymentType": "CARD",
                            "currency": "USD",
                            "settlementCurrency": "USD",
                            "statementDescriptor": {
                              "descriptor": "descriptor",
                              "phone": "8932223111"
                            },
                            "terminalType": "ECOM",
                            "users": [
                              {
                                "id": "646a6568-8f65-4973-979e-d9c8b0b2cd9e",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741a",
                                "loginName": "bleusername6042078741a"
                              },
                              {
                                "id": "98ff19e5-f1a0-4347-8a0e-9e06095f4b69",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741b",
                                "loginName": "bleusername6042078741b"
                              },
                              {
                                "id": "a3730d20-0f36-44b0-84e5-996c7fa4ad8d",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741c",
                                "loginName": "bleusername6042078741c"
                              },
                              {
                                "id": "17768dbe-9ba0-4525-8f39-0455ec4e9040",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741d",
                                "loginName": "bleusername6042078741d"
                              },
                              {
                                "id": "90270633-0a37-4ba2-9937-e23649756988",
                                "email": "bleemail604207874@gmail.com",
                                "fullName": "bleusername6042078741e",
                                "loginName": "bleusername6042078741e"
                              }
                            ],
                            "achBankAccount": {
                              "id": "4d18b869-7190-4f32-b0e3-3ab5bf1f6c76",
                              "lastDigits": "38",
                              "routingNumber": "524871232"
                            }
                          }
                        ],
                        "contacts": [
                          {
                            "id": "ab4fa869-77f6-4cea-9149-07a584167fb3",
                            "firstName": "Good",
                            "lastName": "Human1",
                            "phoneNumber": {
                              "countryCode": "+1",
                              "number": "9090909090"
                            },
                            "email": "goodhuman@goodoffice.com"
                          },
                          {
                            "id": "7ef99ef7-867b-48c6-a85d-54b9a55e400f",
                            "firstName": "Good",
                            "lastName": "Human1",
                            "phoneNumber": {
                              "countryCode": "+1",
                              "number": "9090909090"
                            },
                            "email": "goodhuman@goodoffice.com"
                          },
                          {
                            "id": "5da5bb43-3f6b-482c-8f75-d35754e4a4f4",
                            "firstName": "Good",
                            "lastName": "Human1",
                            "phoneNumber": {
                              "countryCode": "+1",
                              "number": "9090909090"
                            },
                            "email": "goodhuman@goodoffice.com"
                          },
                          {
                            "id": "94ade9f0-88a7-49d6-aec1-ffc1fd88545c",
                            "firstName": "Good",
                            "lastName": "Human1",
                            "phoneNumber": {
                              "countryCode": "+1",
                              "number": "9090909090"
                            },
                            "email": "goodhuman@goodoffice.com"
                          },
                          {
                            "id": "7c4cc663-358c-46b9-b3a1-85108ae31dac",
                            "firstName": "Good",
                            "lastName": "Human1",
                            "phoneNumber": {
                              "countryCode": "+1",
                              "number": "9090909090"
                            },
                            "email": "goodhuman@goodoffice.com"
                          }
                        ]
                      }
                    ],
                    "principals": [
                      {
                        "id": "69d9b928-58e2-4a72-97f1-ffd5ff8d23d9",
                        "isApplicant": true,
                        "isControlProng": true,
                        "firstName": "Sophie",
                        "lastName": "Hosoinon1",
                        "dateOfBirth": {
                          "day": 28,
                          "month": 2,
                          "year": 1984
                        },
                        "ssnLastFour": "2234",
                        "positionInCompany": "Chairman",
                        "type": "OWNER",
                        "address": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        }
                      },
                      {
                        "id": "2f0b72a9-6a89-4ce3-a218-efd83bda269b",
                        "isApplicant": false,
                        "isControlProng": false,
                        "firstName": "Sophie",
                        "lastName": "Hosoinon2",
                        "dateOfBirth": {
                          "day": 28,
                          "month": 2,
                          "year": 1984
                        },
                        "ssnLastFour": "2234",
                        "positionInCompany": "Chairman",
                        "type": "OWNER",
                        "address": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        }
                      },
                      {
                        "id": "2d51d504-c34b-4972-8c6d-14af5169ef64",
                        "isApplicant": false,
                        "isControlProng": false,
                        "firstName": "Sophie",
                        "lastName": "Hosoinon3",
                        "dateOfBirth": {
                          "day": 28,
                          "month": 2,
                          "year": 1984
                        },
                        "ssnLastFour": "2234",
                        "positionInCompany": "Chairman",
                        "type": "OWNER",
                        "address": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        }
                      },
                      {
                        "id": "ba76cd7a-d810-4615-8c1e-71fb3b3ec488",
                        "isApplicant": false,
                        "isControlProng": false,
                        "firstName": "Sophie",
                        "lastName": "Hosoinon4",
                        "dateOfBirth": {
                          "day": 28,
                          "month": 2,
                          "year": 1984
                        },
                        "ssnLastFour": "2234",
                        "positionInCompany": "Chairman",
                        "type": "OWNER",
                        "address": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        }
                      },
                      {
                        "id": "a51e39a3-f41d-4784-9104-681bc86e6eba",
                        "isApplicant": false,
                        "isControlProng": false,
                        "firstName": "Sophie",
                        "lastName": "Hosoinon5",
                        "dateOfBirth": {
                          "day": 28,
                          "month": 2,
                          "year": 1984
                        },
                        "ssnLastFour": "2234",
                        "positionInCompany": "Chairman",
                        "type": "OWNER",
                        "address": {
                          "street": "2600 Michelson Drive",
                          "street2": "Suite 1600",
                          "city": "California",
                          "state": "CA",
                          "country": "US",
                          "zip": "90201"
                        }
                      }
                    ]
                  },
                  "termsVersion": [
                    {
                      "region": "US",
                      "termsAndConditions": "10.1"
                    }
                  ]
                }
              ]
            }
            
            
# Data Structures

## Business Legal Entity
+ `businessLegalEntity` (object) - Registered legal entity details.
    + Properties
        + id: `e84ec16a-ec09-493f-9986-bc0aff2c6b23` (string) - This is the ID returned in the response. It can be used later to look up or update a merchant.
            _Read Only_
        + type: `Ltd` (enum) -  For Possible values, refer to [Business Type Codes](#businesstypecodes).
            _Optional_
        + legalName: `Isuzu Motors Ltd` (string) - Registered legal name.
            _Mandatory, length<=240_
        + registrationNumber: `F01011` (string) - Company's registration number.
            _Optional_
        + taxIdentificationNumber: `TAX123456` (string) - Company's Tax Identification Number.
            _Optional_
        + description: `Diesel motors and vehicles` (string) - Company's business description.
            _Optional_
        + Include Address
             _Mandatory_
        + Include User
        + Include ACH Bank Account
        + Include BACS Bank Account
        + Include EFT Bank Account
        + Include SEPA Bank Account
        + Include Wire Bank Account
        + Include Principals
        + Include Business Details
             _Mandatory_


## Accounts
+ `accounts` (object) : An array of accounts.
    + Properties
        + id: `100101010` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + `paymentType`: `CARD` (enum) - This is the payment type associated with this request. Possible values are:
            _Optional_
            + Members
                + CARD
                + DD
        + currency: `CAD` (string) - Supported currency for the account. You can use only Paysafe configured currencies. See [Supported Currency Codes](#supportedcurrencycodes).
            _Mandatory_
        + settlementCurrency: USD` (string) - This is the currency selected by the merchant for payout. You can use only Paysafe configured currencies. See [Supported Currency Codes](#supportedcurrencycodes).
            _Optional_
        + `statementDescriptor` (object) 
            + Properties
                + descriptor : `WELLVERSED GOODS PVT` (string) - This is the descriptor of the DBA that appears on the card statement.
                    _Optional_
                + phone: `555 888-9999` (string) - This is the phone number of the account. This cannot contain special characters.
                    _Optional_
        + terminalType: `MOTO` (enum) - Mode of transaction. 
            _Mandatory_
            + Members
                + MOTO - Telephonic authentication or IVRS support
                + ECOM - E-commerce transaction
        + cardTypes: `AM` (enum) - This is the type of card used.
            _Mandatory_
            + Members
                + AM -  American Express
                + DI - Discover
                + JC - JCB
                + MC - Mastercard
                + MD - Maestro
                + SO - Solo
                + VI - Visa
                + VD - Visa Debit
                + VE - Visa Electron
        + `processingOptions` (object)
            + Properties
                + id: `po-1111` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
                + cardType: `AM` (enum) - This is the type of card used.
                    _Optional_
                    + Members
                        + AM -  American Express
                        + DI - Discover
                        + JC - JCB
                        + MC - Mastercard
                        + MD - Maestro
                        + SO - Solo
                        + VI - Visa
                        + VD - Visa Debit
                        + VE - Visa Electron
                + mid: `454545` (string) - MID to be used for specific card types.
                    _Mandatory_
                + tids: `8989` (array) - This is an array of string. TIDS to be used for specific card types.
                    _Mandatory_
        + Include ACH Bank Account
        + Include BACS Bank Account
        + Include EFT Bank Account
        + Include SEPA Bank Account
        + Include Wire Bank Account
        + Include User

## Address 
+ `address` (object) : Details of the address.
    + Properties
        + id: `address-1111` (string) This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + street: `100 Queen Street West` (string) - This is the first line of the street address.
             _Mandatory_
        + street2: `Apt. 245` (string) - This is the second line of the street address.
            _Optional_
        + city: `Toronto` (string) - This is the city where the address is located.
             _Mandatory_
        + state: `ON` (string) - This is the state/province/region of the address. For Canada see [Province Codes](#provincecodes). For US see [State Codes](#statecodes).
             _Mandatory_
        + country: `CA` (string) - This is the [country code](#countrycodes) of the address.
             _Mandatory_
        + zip: `M5H 2N2` (string) - This is the zip/postal code of the address. This cannot contain special characters.
             _Mandatory_

## Business Details
+ `businessDetails` (object):  Array of Business Details.
    + Properties
        +  id: `bd-1111` (string) - This is the ID returned in the response. It can be used later to look up or update a merchant.
            _Read Only_
        + tradeName: `Good Office Services USA` (string) - DBA name of the business.
            _Mandatory_
        + `tradeAddress` (object) - Registered Trade address.
            _Optional_
            + Properties
                + Include Address
        + category: `offline` (enum) - This is the category code of the business. See [Merchant Category Codes](#merchantcategorycodes).
            _Mandatory_
        + mcc: `4678` (string) - This is the merchant category code. This is required if the category is not mentioned.
            _Optional_
        + website: `https://goodoffice.us` (string) - This is the business website of the merchant.
            _Optional_
        + Include Phone Number
            _Mandatory_
        + email: `support@goodoffice.us` (string) - This is the customer support email.
            _Mandatory_
        + Include User
        + Include ACH Bank Account
        + Include BACS Bank Account
        + Include EFT Bank Account
        + Include SEPA Bank Account
        + Include Wire Bank Account
        + Include Accounts
            _Mandatory_
        + Include Contacts
            _Mandatory_

## Contacts
+ `contacts` (object) - Array of Contacts.
    + Properties
        + id:  `e84gc1` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + type: `SALES` (enum) - This indicates the type of contact. 
            _Optional_
            + Members
                + SALES
                + BUSINESS
                + PRIMARY
                + CUSTOMER_SERVICE
                + TECH
        + title: `MR` (enum) - This indicates gender or marital status. Possible values are: MR, MRS, MS.
            _Optional_
        + firstName: `James` (string) - This is the first name of the business owner.
            _Mandatory_
        + middleName: `Robert` (string) - This is the middle name of the business owner.
            _Optional_
        + lastName: `Ronald` (string) - This is the last name of the business owner.
            _Mandatory_
        + email: `jamesr@email.com` (string) - This is the email address of the business owner.
            _Mandatory_
        + Include Phone Number
            _Mandatory_             

## SEPA Bank Account
+ `sepaBankAccount` (object) : Details of the SEPA Bank Account.
    + Properties
        + id: `e84fl1` (string) - This is the merchant's bank account ID returned by Paysafe that can be used later to look up or update that merchant bank account.
            _Read Only_
        + beneficiaryAccountName: `Main` (string) - This is the beneficiary's account name.
            _Mandatory_
        + swiftNumber: `85741236` (string) - This is the swift number of the merchant's bank account. Alphanumeric characters only.
            _Mandatory_
        + ibanNumber: `94001521002421` (string) - This is the IBAN of the merchant's bank account. Alphanumeric characters only.
            _Mandatory_
        + lastDigits: `2421` (string) - This is the last 4-digits of account number sent in response.
            _Read Only_
        + beneficiaryBankCountry: `GB` (string) - This is the [country](#sepacountries) of the beneficiary bank's address.
            _Mandatory_

## Principals
+ `principals` (object) : Array of Principals.
    + Properties
        + id: `ph-1111` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + isDirector: `false` (boolean) - This is the country code of customer support phone number.
            _Optional_
        + isApplicant: `true` (boolean) - This is the Customer support phone number.
            _Optional_
        + isControlProng: `false` (boolean) - This indicates whether this person is the Control Prong.
            _Optional_
        + title: `MR` (string) - This indicates profession or marital status. Possile values are: MR, MRS, MS, Jr, Dr.
            _Optional_
        + firstName: `466441111` (string) - This is the first name of the business owner.
            _Optional_
        + middleName: `ph-1111` (string) - This is the middle name of the business owner.
            _Optional_
        + lastName: `81` (string) - This is the last name of the business owner.
            _Optional_
        + previousLastName: `Doe` (string) - This is the previous last name of the business owner. **Note:** This is used for European business owners only.
            _Optional_
        + email: `acscv@email.com` (string) - This is the email address of the business owner.
            _Optional_
        + Include Date of Birth
        + nationality: `466441111` (enum) - This is the nationality code of the business owner. **Note:** This is used for European business owners only.<br/> See [Nationality Codes](#nationalitycodes).
            _Optional_
        + type: `466441111` (enum) - Possible values are: 
            + Members
                + OWNER
                + DIRECTOR
                + TRUSTEE
                + PARTNER
                + SENIOR_MANAGER
                + CONTROL_PRONG
            _Optional_
        + ssn: `123456789` (string) - This is the Social Security Number of the person.
            _Optional_
        + ssnLastFour: `6789` (string) - This is the last 4 digits of SSN sent in response.   
            _Read Only_
        + sin: `466441111` (string) - This is the Social Insurance Number of the person.
            _Optional_
        + sinLastFour: `1111` (string) - This is the last 4 digits of SIN sent in response.
            _Read Only_
        + positionInCompany: `CEO` (string) - This is the position of the person in the company. 
            _Optional_
        + percentageShareholding: `30` (string) - This is the percentage of ownership by the business owner.
            _Optional_



## User
+ `users` (object) - An array of user.
    + Properties 
        + id: `user12` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + email: `johnsmith@email.com` (string) - This is the email address that will be associated with the user.
            _Mandatory_
        + fullName: `John Smith` (string) - This is the full name of the user.
            _Mandatory_
        + loginName: `john_smith` (string) - This is the user that will be configured to access the merchant account in the Merchant Back Office.
            _Mandatory_
        + password: `Pwd1234!` (string) - This is the password that the user will use to access the merchant account in the Merchant Back Office.
            _Mandatory_

## Wire Bank Account
+ `wireBankAccount` (object) : Details of the Wire Bank Account.
    + Properties
        + id: `e84fm1` (string) - This is the merchant's wire bank account ID returned by Paysafe that can be used later to look up or update that merchant bank account.
            _Read Only_
        + accountNumber: `6358555211214` (string) - This is the merchant's bank account number.
            _Mandatory_
        + lastDigits: `1214` (string) - This is the last 4-digits of account number sent in response.
            _Read Only_
        + routingNumber: `1328514` (string) - This is the routing number or the bank code of the merchant's bank account.
            _Optional_
        + sortCode: `857412` (string) - This is the 6-digit sort code of the merchant's bank account. 
            _Optional_
        + swiftNumber: `85774412` (string) - This is the swift number of the merchant's bank account. Alphanumeric characters only.
            _Mandatory_
        + ibanNumber: `94001521002421` (string) - This is the IBAN  of the merchant's bank account. Alphanumeric characters only.
            **Note:** This field is required when *beneficiaryBankCountry* is  within our [SEPA supported countries list](#sepacountries).
            _Optional_
        + beneficiaryCountry: `GB` (string) - This is the [country](#countrycodes) of the beneficiary's address. 
            _Mandatory_
        + beneficiaryAccountName: `Main Account` (string) - This is the beneficiary's account name.
            _Mandatory_
        + beneficiaryAddress: `99 Spalding Green` (string) - This is the beneficiary's address.
            _Mandatory_
        + beneficiaryCity: `London` (string) - This is the beneficiary's city.
            _Mandatory_
        + beneficiaryRegion: `London` (string) - This is the beneficiary's region, state, or province.
            _Mandatory_
        + beneficiaryPostCode: `E15 1AA` (string) - This is the beneficiary's post code.
            _Mandatory_
        + beneficiaryBankCountry: `GB` (string) - This is the [country](#countrycodes) of the beneficiary bank's address.
            _Mandatory_
        + beneficiaryBankName: `First Royal` (string) - This is the name of the beneficiary's bank.
            _Mandatory_
        + beneficiaryBankAddress: `12 Field Rd.` (string) - This is the street of the beneficiary's bank address.
            _Mandatory_
        + beneficiaryBankCity: `London` (string) - This is the city of the beneficiary's bank.
            _Mandatory_
        + beneficiaryBankRegion: `London` (string) - This is the region, state, or province of the beneficiary's bank.
            _Mandatory_
        + beneficiaryBankPostCode: `A13 1BB` (string) - This is the post code of the beneficiary's bank.
            _Mandatory_


## ACH Bank Account
+ `achBankAccount` (object) : Details of the ACH Bank Account.
    + Properties
        + id: `e84ea1` (string) - This is the merchant's ACH bank account ID returned in the response.
            _Read Only_
        + lastDigits: `3954` (string) - This is the last 4-digits of the account number sent in response.
            _Read Only_
        + accountNumber: `5807560412853954` (string) - This is the merchant's bank account number.
             _Mandatory_
        + routingNumber: `854117563` (string) - This is the 9-digit routing number of the merchant's bank account.
             _Mandatory_

## BACS Bank Account
+ `bacsBankAccount` (object) : Details of the BACS Bank Account.
    + Properties
        + id: `e84gc1` (string) - This is the merchant's BACS bank account ID returned in the response.
            _Read Only_
        + accountNumber: `94001521` (string) - This is the merchant's 8-digit bank account number.
             _Mandatory_
        + lastDigits: `1521` (string) - This is the last 4-digits of account number sent in response.
            _Read Only_
        + beneficiaryAccountName: `Main` (string) - This is the beneficiary's account name.
             _Mandatory_
        + beneficiaryBankCountry: `GB` (string) - This is the [country](#bacscountries) of the beneficiary bank's address.
             _Mandatory_
        + sortCode: `857412` (string) - This is the 6-digit sort code of the merchant's bank account.
             _Mandatory_
             


## EFT Bank Account
+ `eftBankAccount` (object) : Details of the EFT Bank Account.
    + Properties
        + id: `e84fc1` (string) - This is the merchant's EFT bank account ID returned in the response.
            _Read Only_
        + accountNumber: `5807560412853954` (string) - This is the merchant's bank account number.
            _Mandatory_
        + lastDigits: `3954` (string) - This is the last 4-digits of account number sent in response.
            _Read Only_
        + transitNumber: `52487` (string) - This is the 5-digit transit number of the merchant's bank branch.
            _Mandatory_
        + institutionId: `052` (string) - This is the 3-digit institution ID of the merchant's bank branch.
            _Mandatory_
        + paymentToken: `1123gdrdt6y` (string) - This is a token generated by Paysafe that represents the bank account.
            _Mandatory_
             


## Date of Birth
+ `dateOfBirth` (object) : Details of the Date of birth.
    + Properties
        + day: `19` (string) - This is the day of the month.
            _Mandatory_
        + month: `12` (string) - This is the month of the year.
            _Mandatory_
        + year: `1990` (string) - This is the year.
            _Mandatory_
            


## Phone Number
+ `phoneNumber` (object) : Details of the phone number.
    + Properties
        + id: `ph-1111` (string) - This is the unique ID returned in the response after some delay. This ID can be used for future associated requests.
            _Read Only_
        + countryCode: `81` (string) - This is the country code of customer support phone number.
            _Mandatory_
        + number: `466441111` (string) - This is the Customer support phone number.
            _Mandatory_

## SubmitBatchObject
+ id:`100001556` (string) - This is the unique ID returned in the response after some delay. It can be used later to look up or update a merchant.
    _Read Only_
+ name:`XYZ` (string) - This is the suitable name given to the application.
    _Optional_
+ merchantRefNum: `merchantRefNum8` (string) - The merchant's unique identifier for this request.
    _Mandatory_
+ onboardingConfigId: `224112` (string) - Merchant onboarding configuration ID that is configured in Paysafe.
    _Mandatory_
+ locale: `en` (string) - Preferred [language/locale](#locale) for this application. Default is "en".
    _Optional_
+ applicationType: `INITIAL_APPLICATION` (enum) - Describes the current status of the application. Default is INITIAL_APPLICATION. 
    _Optional_
    + Members
        + INITIAL_APPLICATION - This denotes a fresh new application
        + ADD_LOCATION - Add a new location to an existing application
        + ADD_ACCOUNT - Add a new account to an existing application
+ acceptTermsAndConditions: `true` (boolean) - True- This indicates that the merchant has accepted the terms and conditions. false - Indicates that the merchant has not accepted the terms and conditions.
    _Optional_
+ Include Business Legal Entity
+ addendum: `` (string) - Additional key-values.
    __Optional, length=10_
+ submit: `true` (boolean) - True - This indicates that the application is submitted and ready for further processing. false - This indicates that the application is still in progress and not ready for further processing.
    _Optional_